---
name: Gradle_Build

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        java: [1.8, 11]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_version: 6.8.3 # set to empty to build with most recent version of gradle
      gradle_commands: build # default is build
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: jburel/action-gradle@v1
        with:
          java-version: ${{ matrix.java }}
          gradle-version: ${{ env.gradle_version }}
      - name: Run commands
        run: ./gradlew ${{ env.gradle_commands }}
