---
name: Gradle_Build

on:
  workflow_call:
    inputs:
      gradle-version:
        required: false
        default: 6.8.3
        type: string
      gradle-commands:
        required: false
        default: build
        type: string
      install-ice:
        required: false
        default: false
        type: string


jobs:
  build:
    strategy:
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      ICE_HOME: /opt/ice-3.6.5
    steps:
      - uses: actions/checkout@v3
      - name: Install Ice and Ice python binding
        uses: ome/action-ice@v1
        if: ${{ inputs.install-ice == 'true' && startsWith(matrix.os, 'ubuntu-latest') }}
      - name: Set up environment
        uses: ome/action-gradle@v2
        with:
          java-version: ${{ matrix.java }}
          gradle-version: ${{ inputs.gradle-version }}
        if: |
          (startsWith(matrix.os, 'ubuntu-latest')) ||
          (inputs.install-ice == 'false')
      - name: Run commands
        run: ./gradlew ${{ inputs.gradle-commands }}
        if: |
          (startsWith(matrix.os, 'ubuntu-latest')) ||
          (inputs.install-ice == 'false')
