---
name: Gradle_Build

on:
  workflow_call:
    inputs:
      gradle-version:
        required: false
        default: 6.8.3
      gradle-commands:
        required: false
        default: build


jobs:
  build:
    strategy:
      matrix:
        java: [1.8, 11]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ome/action-gradle@v1
        with:
          java-version: ${{ matrix.java }}
          gradle-version: ${{ inputs.gradle-version }}
      - name: Run commands
        run: ./gradlew ${{ inputs.gradle-commands }}
